In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
results_df = pd.read_csv("../data/archive/results.csv")
names_df = pd.read_csv("../data/archive/former_names.csv")
shootouts_df = pd.read_csv("../data/archive/shootouts.csv")
goalscorers_df = pd.read_csv("../data/archive/goalscorers.csv")

In [3]:
results_df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49489,2026-07-02,Switzerland,Algeria,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49490,2026-07-03,Australia,Egypt,NaN,NaN,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,NaN,NaN,FIFA World Cup,Houston,United States,True

In [4]:
names_df

,current,former,start_date,end_date
0,Benin,Dahomey,1959-11-08,1975-11-30
1,Burkina Faso,Upper Volta,1960-04-14,1984-08-04
2,Curaçao,Netherlands Antilles,1957-03-03,2010-10-10
3,Czechoslovakia,Bohemia,1903-04-05,1919-01-01
4,Czechoslovakia,Bohemia and Moravia,1939-01-01,1945-05-01
5,Czechoslovakia,Representation of Czechs and Slovaks,1993-03-24,1993-11-17
6,DR Congo,Belgian Congo,1948-05-25,1956-01-02
7,DR Congo,Congo-Léopoldville,1963-04-12,1964-07-19
8,DR Congo,Congo-Kinshasa,1965-01-09,1970-11-24
9,DR Congo,Zaïre,1971-01-10,1997-04-27
10,Djibouti,French Somaliland,1947-12-05,1977-06-27
11,Egypt,United Arab Republic,1958-02-22,1971-09-11
12,Eswatini,Swaziland,1968-05-01,2018-04-19
13,Ghana,Gold Coast,1950-05-28,1957-03-06
14,Guinea-Bissau,Portuguese Guinea,1953-06-02,1973-09-24
15,Guyana,British Guiana,1905-07-21,1967-08-02
16,Indonesia,Dutch East Indies,1934-05-13,1951-03-04
17,Israel,Mandatory Palestine,1934-03-16,1940-04-27
18,Malawi,Nyasaland,1957-08-28,1964-07-04
19,Malaysia,Malaya,1948-06-20,1963-08-16
20,Myanmar,Burma,1952-03-14,1989-01-01
21,North Macedonia,Macedonia,1993-10-13,2018-11-19
22,Northern Ireland,Ireland,1882-02-18,1956-04-11
23,Republic of Ireland,Irish Free State,1924-05-28,1936-12-06
24,Republic of Ireland,Éire,1937-01-01,1953-03-25
25,Russia,Soviet Union,1924-11-16,1991-11-13
26,Russia,CIS,1992-01-25,1992-06-18
27,Samoa,Western Samoa,1979-08-31,1996-11-15
28,Serbia,FR Yugoslavia,1994-12-23,2003-02-03
29,Serbia,Serbia and Montenegro,2003-02-04,2006-06-21
30,Sri Lanka,Ceylon,1952-03-24,1972-05-22
31,Suriname,Dutch Guyana,1921-01-28,1975-11-25
32,Tanzania,Tanganyika,1945-01-01,1964-04-26
33,Vanuatu,New Hebrides,1951-10-04,1980-07-30
34,Zambia,Northern Rhodesia,1947-02-22,1964-10-25
35,Zimbabwe,Southern Rhodesia,1946-06-16,1980-04-18

In [5]:
goalscorers_df

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False
...,...,...,...,...,...,...,...,...
47824,2026-06-29,Brazil,Japan,Brazil,Gabriel Martinelli,90.0,False,False
47825,2026-06-29,Germany,Paraguay,Paraguay,Julio Enciso,42.0,False,False
47826,2026-06-29,Germany,Paraguay,Germany,Kai Havertz,54.0,False,False
47827,2026-06-29,Netherlands,Morocco,Netherlands,Cody Gakpo,72.0,False,False
47828,2026-06-29,Netherlands,Morocco,Morocco,Issa Diop,90.0,False,False

In [6]:
shootouts_df

,date,home_team,away_team,winner,first_shooter
0,1967-08-22,India,Taiwan,Taiwan,NaN
1,1971-11-14,South Korea,Vietnam Republic,South Korea,NaN
2,1972-05-07,South Korea,Iraq,Iraq,NaN
3,1972-05-17,Thailand,South Korea,South Korea,NaN
4,1972-05-19,Thailand,Cambodia,Thailand,NaN
...,...,...,...,...,...
675,2026-03-31,Bosnia and Herzegovina,Italy,Bosnia and Herzegovina,Bosnia and Herzegovina
676,2026-03-31,Czech Republic,Denmark,Czech Republic,Denmark
677,2026-06-06,Lithuania,Latvia,Lithuania,Lithuania
678,2026-06-29,Germany,Paraguay,Paraguay,Germany
679,2026-06-29,Netherlands,Morocco,Morocco,Netherlands